# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  database: cad_project

development:
  <<: *default
  username: <%= ENV['DEV_DB_USERNAME'] %>
  password: <%= ENV['DEV_DB_PASSWORD'] %>
  host: <%= ENV['DEV_DB_HOST'] %>
  port: <%= ENV['DEV_DB_PORT'] %>

test:
  <<: *default
  username: <%= ENV['TEST_DB_USERNAME'] %>
  password: <%= ENV['TEST_DB_PASSWORD'] %>
  host: <%= ENV['TEST_DB_HOST'] %>
  port: <%= ENV['TEST_DB_PORT'] %>
    #  database: db/test.sqlite3

production:
  <<: *default
  username: <%= ENV['PROD_DB_USERNAME'] %>
  password: <%= ENV['PROD_DB_PASSWORD'] %>
  host: <%= ENV['PROD_DB_HOST'] %>
  port: <%= ENV['PROD_DB_PORT'] %>
    #  database: db/production.sqlite3
